@extends('Platform.layouts.app')
@section('title', 'Administrar '.$tenant->slug)
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('platform.tenants.index') }}">← Clientes</a><h1 class="platform-title mt-2">{{ $tenant->slug }}</h1><p class="platform-subtitle">{{ $tenant->domains->first()?->domain }} · {{ $tenant->database_name }}</p></div>
<form class="d-flex gap-2 align-items-center" method="POST" action="{{ route('platform.tenants.status', $tenant) }}">@csrf @method('PATCH')<select class="form-select form-select-sm" name="status">@foreach(['active'=>'Activo','inactive'=>'Inactivo','suspended'=>'Suspendido'] as $value=>$label)<option value="{{ $value }}" @selected($tenant->status===$value)>{{ $label }}</option>@endforeach</select><button class="btn btn-sm btn-outline-primary">Actualizar estado</button></form></div>
<div class="row g-4">
<div class="col-xl-8"><div class="platform-card"><div class="platform-card__head d-flex justify-content-between align-items-center"><div><strong>Módulos habilitados</strong><div class="platform-subtitle">Controla qué accesos estarán disponibles dentro del tenant.</div></div><span class="badge bg-label-primary">{{ $modules->where('company_status', 'active')->count() }} / {{ $modules->count() }}</span></div><div class="platform-card__body">
<form method="POST" action="{{ route('platform.tenants.modules', $tenant) }}">@csrf @method('PUT')
@foreach($modules->groupBy('category_name') as $category => $categoryModules)<div class="mb-4"><div class="small fw-semibold text-uppercase text-muted mb-2">{{ $category }}</div>
@foreach($categoryModules->groupBy('section_name') as $section => $sectionModules)<div class="platform-module-section mb-2"><div class="platform-module-section__title">{{ $section }}</div><div class="platform-module-grid">
@foreach($sectionModules as $module)<label class="platform-module"><input class="form-check-input mt-1" type="checkbox" name="modules[]" value="{{ $module->id }}" @checked($module->company_status==='active')><span><strong class="small">{{ $module->dom_label }}</strong><small>{{ $module->group_name ?: 'Acceso directo' }}</small></span></label>@endforeach
</div></div>@endforeach</div>@endforeach
<div class="text-end"><button class="btn platform-btn-primary text-white">Guardar módulos</button></div></form></div></div></div>
<div class="col-xl-4"><div class="platform-card mb-4"><div class="platform-card__head"><strong>Publicar aviso</strong><div class="platform-subtitle">Se mostrará en la parte superior del tenant.</div></div><div class="platform-card__body"><form method="POST" action="{{ route('platform.tenants.announcements.store', $tenant) }}">@csrf
<div class="mb-3"><label class="form-label">Título</label><input class="form-control" name="title" required></div><div class="mb-3"><label class="form-label">Mensaje</label><textarea class="form-control" rows="4" name="message" required></textarea></div><div class="row g-2"><div class="col-6"><label class="form-label">Tipo</label><select class="form-select" name="severity"><option value="info">Información</option><option value="success">Éxito</option><option value="warning">Advertencia</option><option value="danger">Importante</option></select></div><div class="col-6 d-flex align-items-end pb-2"><label class="form-check"><input class="form-check-input" type="checkbox" name="dismissible" value="1" checked><span class="form-check-label">Descartable</span></label></div><div class="col-6"><label class="form-label">Desde</label><input class="form-control" type="datetime-local" name="starts_at"></div><div class="col-6"><label class="form-label">Hasta</label><input class="form-control" type="datetime-local" name="ends_at"></div></div><button class="btn platform-btn-primary text-white w-100 mt-3">Publicar aviso</button></form></div></div>
<div class="platform-card"><div class="platform-card__head"><strong>Avisos</strong></div><div class="platform-card__body">@forelse($announcements as $announcement)<div class="border-bottom pb-3 mb-3"><div class="d-flex justify-content-between gap-2"><strong class="small">{{ $announcement->title }}</strong><span class="platform-status platform-status--{{ $announcement->status }}">{{ $announcement->status }}</span></div><p class="small text-muted my-2">{{ $announcement->message }}</p><form method="POST" action="{{ route('platform.tenants.announcements.status', [$tenant, $announcement]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $announcement->status==='active'?'inactive':'active' }}"><button class="btn btn-sm btn-link px-0">{{ $announcement->status==='active'?'Desactivar':'Activar' }}</button></form></div>@empty<p class="small text-muted mb-0">Sin avisos publicados.</p>@endforelse</div></div></div>
</div>
@endsection
